name: SBOM upload for Single Project

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    # Step 3: Generate SBOM for Datahub.Core using CycloneDX
    - name: Generate JSON SBOM for Datahub.Core
      uses: CycloneDX/gh-dotnet-generate-sbom@master
      with:
        path: ./Portal/src/Datahub.Core/Datahub.Core.csproj
        json: true
        github-bearer-token: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Upload SBOM for Datahub.Core
    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: datahub-core-sbom
        path: ./bom.json

    # Step 5: Submit SBOM (optional)
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@v0.1.1
      with:
        filePath: ./bom.json