name: SBOM upload for Monorepo Projects

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    # Step 3: Find and build all .csproj files in Portal
    - name: Find and build .csproj files in Portal
      run: |
        find ./Portal/src -name "*.csproj" | while read csproj; do
          echo "Building $csproj"
          dotnet build "$csproj" --output ./Portal/buildOutput
        done

    # Step 4: Generate SBOM for Portal after building
    - name: Generate SBOM for Portal
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        mkdir -p ./Portal/_sbom_output
        $RUNNER_TEMP/sbom-tool generate -b ./Portal/buildOutput -bc ./Portal/src -pn "Portal" -pv "1.0.0" -ps "OwnerName" -nsb "https://sbom.mycompany.com" -V Verbose

    # Step 5: Upload SBOM for Portal
    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: portal-sbom
        path: ./Portal/_sbom_output/_manifest/spdx_2.2/manifest.spdx.json

    # Step 6: Submit SBOM (optional)
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@v0.1.1
      with:
        filePath: ./Portal/_sbom_output/_manifest/spdx_2.2/manifest.spdx.json