name: Pull Request Workflow

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  prep:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history to get the commits we need
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Get list of changed files as JSON
      - name: Get list of changed files as JSON
        id: get_files
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          JSON_FILES=$(echo "$FILES" | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$JSON_FILES" >> $GITHUB_OUTPUT

      # Step 3: Set boolean flags for changes in specific directories
      - name: Set directory change flags
        id: set_flags
        run: |
          FILES_JSON='${{ steps.get_files.outputs.files }}'
          PORTAL_CHANGED=false
          RESOURCEPROVISIONER_CHANGED=false
          SERVERLESSOPERATIONS_CHANGED=false

          for FILE in $(echo "$FILES_JSON" | jq -r '.[]'); do
            if [[ "$FILE" =~ ^Portal/ ]]; then
              PORTAL_CHANGED=true
            elif [[ "$FILE" =~ ^ResourceProvisioner/ ]]; then
              RESOURCEPROVISIONER_CHANGED=true
            elif [[ "$FILE" =~ ^ServerlessOperations/ ]]; then
              SERVERLESSOPERATIONS_CHANGED=true
            fi
          done

          echo "portal_changed=$PORTAL_CHANGED" >> $GITHUB_OUTPUT
          echo "resourceprovisioner_changed=$RESOURCEPROVISIONER_CHANGED" >> $GITHUB_OUTPUT
          echo "serverlessoperations_changed=$SERVERLESSOPERATIONS_CHANGED" >> $GITHUB_OUTPUT

      # Step 4: List all changed files
      - name: List all changed files
        run: |
          FILES_JSON='${{ steps.get_files.outputs.files }}'
          echo "Changed files:"
          echo "$FILES_JSON" | jq -r '.[]'

  build:
    runs-on: ubuntu-latest
    needs: prep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 5: Find and build changed projects
      - name: Find and build changed projects
        if: needs.prep.outputs.get_files.files != '[]'
        run: |
          FILES_JSON='${{ needs.prep.outputs.get_files.files }}'
          PROJECTS_TO_BUILD=()

          # Check if any files in the specified directories have changed
          for FILE in $(echo "$FILES_JSON" | jq -r '.[]'); do
            if [[ "$FILE" =~ ^(Portal|ResourceProvisioner|ServerlessOperations)/src/([^/]+)/.* ]]; then
              PROJECT_PATH=$(echo "$FILE" | grep -oE '^(Portal|ResourceProvisioner|ServerlessOperations)/src/[^/]+')
              CSPROJ_PATH=$(find "$PROJECT_PATH" -name "*.csproj" | head -n 1)
              if [ -n "$CSPROJ_PATH" ]; then
                PROJECTS_TO_BUILD+=("$CSPROJ_PATH")
              fi
            fi
          done

          if [ ${#PROJECTS_TO_BUILD[@]} -eq 0 ]; then
            echo "No projects need to be built. Skipping build step."
            exit 0
          else
            echo "The following projects will be built:"
            for PROJECT in "${PROJECTS_TO_BUILD[@]}"; do
              echo " - $PROJECT"
            done
            for PROJECT in "${PROJECTS_TO_BUILD[@]}"; do
              echo "Restoring dependencies for project: $PROJECT"
              dotnet restore "$PROJECT"
              echo "Building project: $PROJECT"
              dotnet build "$PROJECT" /warnaserror:none
            done
          fi
